### ISSUE TITLE
add support to Control fan speed

### ISSUE THREAD

**Issue by Sayor0630** [Lorys89/SMCProcessorAMD#7]

**Comment by Lorys89** [comment]
It must be done on smc super io

**Comment by Sayor0630** [comment]
> It must be done on smc super io

Then add frequency Data

**Comment by Lorys89** [comment]
This kext is for temp and watt and should be used in conjunction with smcsuperio for fan reading.

**Comment by Sayor0630** [comment]
> This kext is for temp and watt and should be used in conjunction with smcsuperio for fan reading.

then there is no way for frequency?

**Comment by Lorys89** [comment]
Virtualsmc has no keys for the cpu freq

**Comment by Sayor0630** [comment]
> Virtualsmc has no keys for the cpu freq

Then is there any way to add support for [Stats](https://github.com/exelban/stats) app which is found on github? It already can get CPU frequency from [Intel Power Gadget](https://www.intel.com/content/www/us/en/developer/articles/tool/power-gadget.html). maybe add something for it to read frequency?
You can collab with [SMCAMDProcessor](https://github.com/trulyspinach/SMCAMDProcessor). I know your project is inpire by his. But its just I am saying..

**Comment by Lorys89** [comment]
Already tried in the past, you can't have virtual smc publish the frequency keys, fakesmc does it, but it's an obsolete method, and I don't care to work on it, use SMCAMDProcessor app if you like, but you can't have the keys on virtual smc.

**Comment by Lorys89** [comment]
And I'm not going to talk about it any further, it's not feasible on this kext.
